backtest:
  initial_cash: 100000.0
  risk_percent: 2.0
  commission: 0.001

strategy:
  dbb:
    max_position_size: 0.5
    entry_threshold: 1.0
    exit_threshold: 1.0

data:
  default_symbol: 'BTC'
  default_interval: '1d'
  data_dir: 'data'

output:
  results_dir: 'results'
  plots_dir: 'plots'